import math
from typing import Tuple
import paddle
import numpy as np
from paddle.nn.initializer import TruncatedNormal, Constant
from einops import rearrange, repeat

ACTIVATION = {'gelu': paddle.nn.GELU, 'tanh': paddle.nn.Tanh, 'sigmoid':
    paddle.nn.Sigmoid, 'relu': paddle.nn.ReLU, 'leaky_relu': paddle.nn.
    LeakyReLU(negative_slope=0.1), 'softplus': paddle.nn.Softplus, 'ELU':
                  paddle.nn.ELU, 'silu': paddle.nn.Silu}


# This file is generated by PaConvert ToolKit, please Don't edit it!

def reshape(self, *args, **kwargs):
    if args:
        if len(args) == 1 and isinstance(args[0], (tuple, list)):
            return paddle.reshape(self, args[0])
        else:
            return paddle.reshape(self, list(args))
    elif kwargs:
        assert 'shape' in kwargs
        return paddle.reshape(self, shape=kwargs['shape'])


setattr(paddle.Tensor, 'reshape', reshape)


def min_class_func(self, *args, **kwargs):
    if 'other' in kwargs:
        kwargs['y'] = kwargs.pop('other')
        ret = paddle.minimum(self, *args, **kwargs)
    elif len(args) == 1 and isinstance(args[0], paddle.Tensor):
        ret = paddle.minimum(self, *args, **kwargs)
    else:
        if 'dim' in kwargs:
            kwargs['axis'] = kwargs.pop('dim')

        if 'axis' in kwargs or len(args) >= 1:
            ret = paddle.min(self, *args, **kwargs), paddle.argmin(self, *args, **kwargs)
        else:
            ret = paddle.min(self, *args, **kwargs)

    return ret


def max_class_func(self, *args, **kwargs):
    if 'other' in kwargs:
        kwargs['y'] = kwargs.pop('other')
        ret = paddle.maximum(self, *args, **kwargs)
    elif len(args) == 1 and isinstance(args[0], paddle.Tensor):
        ret = paddle.maximum(self, *args, **kwargs)
    else:
        if 'dim' in kwargs:
            kwargs['axis'] = kwargs.pop('dim')

        if 'axis' in kwargs or len(args) >= 1:
            ret = paddle.max(self, *args, **kwargs), paddle.argmax(self, *args, **kwargs)
        else:
            ret = paddle.max(self, *args, **kwargs)

    return ret


setattr(paddle.Tensor, "min", min_class_func)
setattr(paddle.Tensor, "max", max_class_func)


def transpose_aux_func(dims, dim0, dim1):
    perm = list(range(dims))
    perm[dim0], perm[dim1] = perm[dim1], perm[dim0]
    return perm


def add(self, *args, **kwargs):
    if 'other' in kwargs:
        y = kwargs['other']
    elif 'y' in kwargs:
        y = kwargs['y']
    else:
        y = args[0]

    if 'alpha' in kwargs:
        alpha = kwargs['alpha']
        if alpha != 1:
            if not isinstance(y, paddle.Tensor):
                y = paddle.to_tensor(alpha * y)
            else:
                y = alpha * y
    else:
        if not isinstance(y, paddle.Tensor):
            y = paddle.to_tensor(y)

    return paddle.add(self, y)


setattr(paddle.Tensor, 'add', add)


def view(self, *args, **kwargs):
    if args:
        if len(args) == 1 and isinstance(args[0], (tuple, list, str)):
            return paddle.view(self, args[0])
        else:
            return paddle.view(self, list(args))
    elif kwargs:
        return paddle.view(self, shape_or_dtype=list(kwargs.values())[0])


setattr(paddle.Tensor, 'view', view)


class Physics_Attention_Irregular_Mesh_ShapeNetCar(paddle.nn.Layer):

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0, slice_num=64):
        super().__init__()
        inner_dim = dim_head * heads
        self.dim_head = dim_head
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.softmax = paddle.nn.Softmax(axis=-1)
        self.dropout = paddle.nn.Dropout(p=dropout)
        self.temperature = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=paddle.ones(shape=[1, heads, 1, 1]) * 0.5)
        self.in_project_x = paddle.nn.Linear(in_features=dim, out_features=
        inner_dim)
        self.in_project_fx = paddle.nn.Linear(in_features=dim, out_features
        =inner_dim)
        self.in_project_slice = paddle.nn.Linear(in_features=dim_head,
                                                 out_features=slice_num)
        for l in [self.in_project_slice]:
            init_Orthogonal = paddle.nn.initializer.Orthogonal()
            init_Orthogonal(l.weight)
        self.to_q = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_k = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_v = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_out = paddle.nn.Sequential(paddle.nn.Linear(in_features=
                                                            inner_dim, out_features=dim), paddle.nn.Dropout(p=dropout))

    def forward(self, x):
        B, N, C = tuple(x.shape)
        fx_mid = self.in_project_fx(x).reshape(B, N, self.heads, self.dim_head
                                               ).transpose(perm=[0, 2, 1, 3]).contiguous()
        x_mid = self.in_project_x(x).reshape(B, N, self.heads, self.dim_head
                                             ).transpose(perm=[0, 2, 1, 3]).contiguous()
        slice_weights = self.softmax(self.in_project_slice(x_mid) / self.
                                     temperature)
        slice_norm = slice_weights.sum(axis=2)
        slice_token = paddle.einsum('bhnc,bhng->bhgc', fx_mid, slice_weights)
        slice_token = slice_token / (slice_norm + 1e-05)[:, :, :, None].tile(
            repeat_times=[1, 1, 1, self.dim_head])
        q_slice_token = self.to_q(slice_token)
        k_slice_token = self.to_k(slice_token)
        v_slice_token = self.to_v(slice_token)
        dots = paddle.matmul(x=q_slice_token, y=k_slice_token.transpose(
            perm=transpose_aux_func(k_slice_token.ndim, -1, -2))
                             ) * self.scale
        attn = self.softmax(dots)
        attn = self.dropout(attn)
        out_slice_token = paddle.matmul(x=attn, y=v_slice_token)
        out_x = paddle.einsum('bhgc,bhng->bhnc', out_slice_token, slice_weights
                              )
        out_x = rearrange(out_x, 'b h n d -> b n (h d)')
        return self.to_out(out_x)


class MLP_ShapeNetCar(paddle.nn.Layer):

    def __init__(self, n_input, n_hidden, n_output, n_layers=1, act='gelu',
                 res=True):
        super(MLP_ShapeNetCar, self).__init__()
        if act in ACTIVATION.keys():
            act = ACTIVATION[act]
        else:
            raise NotImplementedError
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output
        self.n_layers = n_layers
        self.res = res
        self.linear_pre = paddle.nn.Sequential(paddle.nn.Linear(in_features
                                                                =n_input, out_features=n_hidden), act())
        self.linear_post = paddle.nn.Linear(in_features=n_hidden,
                                            out_features=n_output)
        self.linears = paddle.nn.LayerList(sublayers=[paddle.nn.Sequential(
            paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
            act()) for _ in range(n_layers)])

    def forward(self, x):
        x = self.linear_pre(x)
        for i in range(self.n_layers):
            if self.res:
                x = self.linears[i](x) + x
            else:
                x = self.linears[i](x)
        x = self.linear_post(x)
        return x


class Transolver_block_ShapeNetCar(paddle.nn.Layer):
    """Transformer encoder block."""

    def __init__(self, num_heads: int, hidden_dim: int, dropout: float, act
    ='gelu', mlp_ratio=4, last_layer=False, out_dim=1, slice_num=32):
        super().__init__()
        self.last_layer = last_layer
        self.ln_1 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.Attn = Physics_Attention_Irregular_Mesh_ShapeNetCar(hidden_dim, heads=
        num_heads, dim_head=hidden_dim // num_heads, dropout=dropout,
                                                                 slice_num=slice_num)
        self.ln_2 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.mlp = MLP_ShapeNetCar(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                                   n_layers=0, res=False, act=act)
        if self.last_layer:
            self.ln_3 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
            self.mlp2 = paddle.nn.Linear(in_features=hidden_dim,
                                         out_features=out_dim)

    def forward(self, fx):
        fx = self.Attn(self.ln_1(fx)) + fx
        fx = self.mlp(self.ln_2(fx)) + fx
        if self.last_layer:
            return self.mlp2(self.ln_3(fx))
        else:
            return fx


class Transolver_ShapeNetCar(paddle.nn.Layer):

    def __init__(self,
                 input_keys: Tuple[str, ...],
                 label_keys: Tuple[str, ...],
                 weight_keys: Tuple[str, ...],
                 space_dim=1,
                 n_layers=5,
                 n_hidden=256,
                 dropout=0,
                 n_head=8,
                 act='gelu',
                 mlp_ratio=1,
                 fun_dim=1,
                 out_dim=1,
                 slice_num=32,
                 ref=8,
                 unified_pos=False):
        super(Transolver_ShapeNetCar, self).__init__()
        self.__name__ = 'UniPDE_3D'
        self.input_keys = input_keys
        self.label_keys = label_keys
        self.weight_keys = weight_keys
        self.ref = ref
        self.unified_pos = unified_pos
        if self.unified_pos:
            self.preprocess = MLP_ShapeNetCar(fun_dim + self.ref * self.ref * self.ref,
                                              n_hidden * 2, n_hidden, n_layers=0, res=False, act=act)
        else:
            self.preprocess = MLP_ShapeNetCar(fun_dim + space_dim, n_hidden * 2,
                                              n_hidden, n_layers=0, res=False, act=act)
        self.n_hidden = n_hidden
        self.space_dim = space_dim
        self.blocks = paddle.nn.LayerList(sublayers=[Transolver_block_ShapeNetCar(
            num_heads=n_head, hidden_dim=n_hidden, dropout=dropout, act=act,
            mlp_ratio=mlp_ratio, out_dim=out_dim, slice_num=slice_num,
            last_layer=_ == n_layers - 1) for _ in range(n_layers)])
        self.initialize_weights()
        self.placeholder = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=1 / n_hidden * paddle.rand(shape=[n_hidden], dtype='float32'))

    def initialize_weights(self):
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, paddle.nn.Linear):
            trunc_normal = TruncatedNormal(mean=0.0, std=0.02)
            trunc_normal(m.weight)
            if m.bias is not None:
                constant = Constant(value=0.0)
                constant(m.bias)
        elif isinstance(m, (paddle.nn.LayerNorm, paddle.nn.BatchNorm1D)):
            constant = Constant(value=0.0)
            constant(m.bias)
            constant = Constant(value=1.0)
            constant(m.weight)

    def get_grid(self, my_pos):
        batchsize = tuple(my_pos.shape)[0]
        gridx = paddle.to_tensor(data=np.linspace(-1.5, 1.5, self.ref),
                                 dtype='float32')
        gridx = gridx.reshape(1, self.ref, 1, 1, 1).tile(repeat_times=[
            batchsize, 1, self.ref, self.ref, 1])
        gridy = paddle.to_tensor(data=np.linspace(0, 2, self.ref), dtype=
        'float32')
        gridy = gridy.reshape(1, 1, self.ref, 1, 1).tile(repeat_times=[
            batchsize, self.ref, 1, self.ref, 1])
        gridz = paddle.to_tensor(data=np.linspace(-4, 4, self.ref), dtype=
        'float32')
        gridz = gridz.reshape(1, 1, 1, self.ref, 1).tile(repeat_times=[
            batchsize, self.ref, self.ref, 1, 1])
        grid_ref = paddle.concat(x=(gridx, gridy, gridz), axis=-1).reshape(batchsize, self.ref ** 3, 3)
        pos = paddle.sqrt(x=paddle.sum(x=(my_pos[:, :, None, :] - grid_ref[
                                                                  :, None, :, :]) ** 2, axis=-1)).reshape(batchsize,
                                                                                                          tuple(my_pos
                                                                                                                .shape)[
                                                                                                              1],
                                                                                                          self.ref * self.ref * self.ref).contiguous()
        return pos

    def forward(self, data):
        # data = data[self.input_keys[0]]
        x, edge_index, pos, surf = data[self.input_keys[0]], data[self.input_keys[1]], data[self.input_keys[3]],  data[self.input_keys[4]],
        # cfd_data = data
        x, fx, T = x, None, None
        x = x[None, :, :]
        if self.unified_pos:
            new_pos = self.get_grid(pos[None, :, :])
            x = paddle.concat(x=(x, new_pos), axis=-1)
        if fx is not None:
            fx = paddle.concat(x=(x, fx), axis=-1)
            fx = self.preprocess(fx)
        else:
            fx = self.preprocess(x)
            fx = fx + self.placeholder[None, None, :]
        for block in self.blocks:
            fx = block(fx)

        return {self.label_keys[0]: fx[0][surf, -1], self.label_keys[1]: fx[0][:, :-1]}


class Physics_Attention_Structured_Mesh_3D(paddle.nn.Layer):

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0, slice_num=32,
                 H=32, W=32, D=32, kernel=3):
        super().__init__()
        inner_dim = dim_head * heads
        self.dim_head = dim_head
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.softmax = paddle.nn.Softmax(axis=-1)
        self.dropout = paddle.nn.Dropout(p=dropout)
        self.temperature = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=paddle.ones(shape=[1, heads, 1, 1]) * 0.5)
        self.H = H
        self.W = W
        self.D = D
        self.in_project_x = paddle.nn.Conv3D(in_channels=dim, out_channels=
        inner_dim, kernel_size=kernel, stride=1, padding=kernel // 2)
        self.in_project_fx = paddle.nn.Conv3D(in_channels=dim, out_channels
        =inner_dim, kernel_size=kernel, stride=1, padding=kernel // 2)
        self.in_project_slice = paddle.nn.Linear(in_features=dim_head,
                                                 out_features=slice_num)
        for l in [self.in_project_slice]:
            init_Orthogonal = paddle.nn.initializer.Orthogonal()
            init_Orthogonal(l.weight)
        self.to_q = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_k = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_v = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_out = paddle.nn.Sequential(paddle.nn.Linear(in_features=
                                                            inner_dim, out_features=dim), paddle.nn.Dropout(p=dropout))

    def forward(self, x):
        B, N, C = tuple(x.shape)
        x = x.reshape(B, self.H, self.W, self.D, C).contiguous().transpose(perm
                                                                           =[0, 4, 1, 2, 3]).contiguous()
        fx_mid = self.in_project_fx(x).transpose(perm=[0, 2, 3, 4, 1]
                                                 ).contiguous().reshape(B, N, self.heads, self.dim_head).transpose(
            perm=[0, 2, 1, 3]).contiguous()
        x_mid = self.in_project_x(x).transpose(perm=[0, 2, 3, 4, 1]
                                               ).contiguous().reshape(B, N, self.heads, self.dim_head).transpose(
            perm=[0, 2, 1, 3]).contiguous()
        slice_weights = self.softmax(self.in_project_slice(x_mid) / paddle.
                                     clip(x=self.temperature, min=0.1, max=5))
        slice_norm = slice_weights.sum(axis=2)
        slice_token = paddle.einsum('bhnc,bhng->bhgc', fx_mid, slice_weights)
        slice_token = slice_token / (slice_norm + 1e-05)[:, :, :, None].tile(
            repeat_times=[1, 1, 1, self.dim_head])
        q_slice_token = self.to_q(slice_token)
        k_slice_token = self.to_k(slice_token)
        v_slice_token = self.to_v(slice_token)
        dots = paddle.matmul(x=q_slice_token, y=k_slice_token.transpose(
            perm=transpose_aux_func(k_slice_token.ndim, -1, -2))
                             ) * self.scale
        attn = self.softmax(dots)
        attn = self.dropout(attn)
        out_slice_token = paddle.matmul(x=attn, y=v_slice_token)
        out_x = paddle.einsum('bhgc,bhng->bhnc', out_slice_token, slice_weights
                              )
        out_x = rearrange(out_x, 'b h n d -> b n (h d)')
        return self.to_out(out_x)


class MLP_Mesh_3D(paddle.nn.Layer):

    def __init__(self, n_input, n_hidden, n_output, n_layers=1, act='gelu',
                 res=True):
        super(MLP_Mesh_3D, self).__init__()
        if act in ACTIVATION.keys():
            act = ACTIVATION[act]
        else:
            raise NotImplementedError
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output
        self.n_layers = n_layers
        self.res = res
        self.linear_pre = paddle.nn.Sequential(paddle.nn.Linear(in_features
                                                                =n_input, out_features=n_hidden), act())
        self.linear_post = paddle.nn.Linear(in_features=n_hidden,
                                            out_features=n_output)
        self.linears = paddle.nn.LayerList(sublayers=[paddle.nn.Sequential(
            paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
            act()) for _ in range(n_layers)])

    def forward(self, x):
        x = self.linear_pre(x)
        for i in range(self.n_layers):
            if self.res:
                x = self.linears[i](x) + x
            else:
                x = self.linears[i](x)
        x = self.linear_post(x)
        return x


class Transolver_block_Mesh_3D(paddle.nn.Layer):
    """Transformer encoder block."""

    def __init__(self, num_heads: int, hidden_dim: int, dropout: float, act
    ='gelu', mlp_ratio=4, last_layer=False, out_dim=1, slice_num=32):
        super().__init__()
        self.last_layer = last_layer
        self.ln_1 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.Attn = Physics_Attention_Structured_Mesh_3D(hidden_dim, heads=
        num_heads, dim_head=hidden_dim // num_heads, dropout=dropout,
                                                         slice_num=slice_num)
        self.ln_2 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.mlp = MLP_Mesh_3D(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                               n_layers=0, res=False, act=act)
        if self.last_layer:
            self.ln_3 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
            self.mlp2 = paddle.nn.Linear(in_features=hidden_dim,
                                         out_features=out_dim)

    def forward(self, fx):
        fx = self.Attn(self.ln_1(fx)) + fx
        fx = self.mlp(self.ln_2(fx)) + fx
        if self.last_layer:
            return self.mlp2(self.ln_3(fx))
        else:
            return fx


class Transolver_Structured_Mesh_3D(paddle.nn.Layer):

    def __init__(self,
                 space_dim=1,
                 n_layers=5,
                 n_hidden=256,
                 dropout=0,
                 n_head=8,
                 act='gelu',
                 mlp_ratio=1,
                 fun_dim=1,
                 out_dim=1,
                 slice_num=32,
                 ref=8,
                 unified_pos=False):
        super(Transolver_Structured_Mesh_3D, self).__init__()
        self.__name__ = 'UniPDE_3D'
        self.ref = ref
        self.unified_pos = unified_pos
        if self.unified_pos:
            self.preprocess = MLP_Mesh_3D(fun_dim + self.ref * self.ref * self.ref,
                                          n_hidden * 2, n_hidden, n_layers=0, res=False, act=act)
        else:
            self.preprocess = MLP_Mesh_3D(fun_dim + space_dim, n_hidden * 2,
                                          n_hidden, n_layers=0, res=False, act=act)
        self.n_hidden = n_hidden
        self.space_dim = space_dim
        self.blocks = paddle.nn.LayerList(sublayers=[Transolver_block_Mesh_3D(
            num_heads=n_head, hidden_dim=n_hidden, dropout=dropout, act=act,
            mlp_ratio=mlp_ratio, out_dim=out_dim, slice_num=slice_num,
            last_layer=_ == n_layers - 1) for _ in range(n_layers)])
        self.initialize_weights()
        self.placeholder = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=1 / n_hidden * paddle.rand(shape=[n_hidden], dtype='float32'))

    def initialize_weights(self):
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, paddle.nn.Linear):
            trunc_normal = TruncatedNormal(mean=0.0, std=0.02)
            trunc_normal(m.weight)
            if m.bias is not None:
                constant = Constant(value=0.0)
                constant(m.bias)
        elif isinstance(m, (paddle.nn.LayerNorm, paddle.nn.BatchNorm1D)):
            constant = Constant(value=0.0)
            constant(m.bias)
            constant = Constant(value=1.0)
            constant(m.weight)

    def get_grid(self, my_pos):
        batchsize = tuple(my_pos.shape)[0]
        gridx = paddle.to_tensor(data=np.linspace(-1.5, 1.5, self.ref),
                                 dtype='float32')
        gridx = gridx.reshape(1, self.ref, 1, 1, 1).tile(repeat_times=[
            batchsize, 1, self.ref, self.ref, 1])
        gridy = paddle.to_tensor(data=np.linspace(0, 2, self.ref), dtype=
        'float32')
        gridy = gridy.reshape(1, 1, self.ref, 1, 1).tile(repeat_times=[
            batchsize, self.ref, 1, self.ref, 1])
        gridz = paddle.to_tensor(data=np.linspace(-4, 4, self.ref), dtype=
        'float32')
        gridz = gridz.reshape(1, 1, 1, self.ref, 1).tile(repeat_times=[
            batchsize, self.ref, self.ref, 1, 1])
        grid_ref = paddle.concat(x=(gridx, gridy, gridz), axis=-1).reshape(batchsize, self.ref ** 3, 3)
        pos = paddle.sqrt(x=paddle.sum(x=(my_pos[:, :, None, :] - grid_ref[
                                                                  :, None, :, :]) ** 2, axis=-1)).reshape(batchsize,
                                                                                                          tuple(my_pos
                                                                                                                .shape)[
                                                                                                              1],
                                                                                                          self.ref * self.ref * self.ref).contiguous()
        return pos

    def forward(self, data):
        cfd_data, geom_data = data
        x, fx, T = cfd_data.x, None, None
        x = x[None, :, :]
        if self.unified_pos:
            new_pos = self.get_grid(cfd_data.pos[None, :, :])
            x = paddle.concat(x=(x, new_pos), axis=-1)
        if fx is not None:
            fx = paddle.concat(x=(x, fx), axis=-1)
            fx = self.preprocess(fx)
        else:
            fx = self.preprocess(x)
            fx = fx + self.placeholder[None, None, :]
        for block in self.blocks:
            fx = block(fx)
        return fx[0]


class Physics_Attention_Structured_Mesh_2D(paddle.nn.Layer):

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0, slice_num=64,
                 H=101, W=31, kernel=3):
        super().__init__()
        inner_dim = dim_head * heads
        self.dim_head = dim_head
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.softmax = paddle.nn.Softmax(axis=-1)
        self.dropout = paddle.nn.Dropout(p=dropout)
        self.temperature = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=paddle.ones(shape=[1, heads, 1, 1]) * 0.5)
        self.H = H
        self.W = W
        self.in_project_x = paddle.nn.Conv2D(in_channels=dim, out_channels=
        inner_dim, kernel_size=kernel, stride=1, padding=kernel // 2)
        self.in_project_fx = paddle.nn.Conv2D(in_channels=dim, out_channels
        =inner_dim, kernel_size=kernel, stride=1, padding=kernel // 2)
        self.in_project_slice = paddle.nn.Linear(in_features=dim_head,
                                                 out_features=slice_num)
        for l in [self.in_project_slice]:
            init_Orthogonal = paddle.nn.initializer.Orthogonal()
            init_Orthogonal(l.weight)
        self.to_q = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_k = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_v = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_out = paddle.nn.Sequential(paddle.nn.Linear(in_features=
                                                            inner_dim, out_features=dim), paddle.nn.Dropout(p=dropout))

    def forward(self, x):
        B, N, C = tuple(x.shape)
        x = x.reshape(B, self.H, self.W, C).contiguous().transpose(perm=[0,
                                                                         3, 1, 2]).contiguous()
        fx_mid = self.in_project_fx(x).transpose(perm=[0, 2, 3, 1]).contiguous(
        ).reshape(B, N, self.heads, self.dim_head).transpose(perm=[0, 2,
                                                                   1, 3]).contiguous()
        x_mid = self.in_project_x(x).transpose(perm=[0, 2, 3, 1]).contiguous(
        ).reshape(B, N, self.heads, self.dim_head).transpose(perm=[0, 2,
                                                                   1, 3]).contiguous()
        slice_weights = self.softmax(self.in_project_slice(x_mid) / paddle.
                                     clip(x=self.temperature, min=0.1, max=5))
        slice_norm = slice_weights.sum(axis=2)
        slice_token = paddle.einsum('bhnc,bhng->bhgc', fx_mid, slice_weights)
        slice_token = slice_token / (slice_norm + 1e-05)[:, :, :, None].tile(
            repeat_times=[1, 1, 1, self.dim_head])
        q_slice_token = self.to_q(slice_token)
        k_slice_token = self.to_k(slice_token)
        v_slice_token = self.to_v(slice_token)
        dots = paddle.matmul(x=q_slice_token, y=k_slice_token.transpose(
            perm=transpose_aux_func(k_slice_token.ndim, -1, -2))
                             ) * self.scale
        attn = self.softmax(dots)
        attn = self.dropout(attn)
        out_slice_token = paddle.matmul(x=attn, y=v_slice_token)
        out_x = paddle.einsum('bhgc,bhng->bhnc', out_slice_token, slice_weights
                              )
        out_x = rearrange(out_x, 'b h n d -> b n (h d)')
        return self.to_out(out_x)


class MLP_Mesh_2D(paddle.nn.Layer):

    def __init__(self, n_input, n_hidden, n_output, n_layers=1, act='gelu',
                 res=True):
        super(MLP_Mesh_2D, self).__init__()
        if act in ACTIVATION.keys():
            act = ACTIVATION[act]
        else:
            raise NotImplementedError
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output
        self.n_layers = n_layers
        self.res = res
        self.linear_pre = paddle.nn.Sequential(paddle.nn.Linear(in_features
                                                                =n_input, out_features=n_hidden), act())
        self.linear_post = paddle.nn.Linear(in_features=n_hidden,
                                            out_features=n_output)
        self.linears = paddle.nn.LayerList(sublayers=[paddle.nn.Sequential(
            paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
            act()) for _ in range(n_layers)])

    def forward(self, x):
        x = self.linear_pre(x)
        for i in range(self.n_layers):
            if self.res:
                x = self.linears[i](x) + x
            else:
                x = self.linears[i](x)
        x = self.linear_post(x)
        return x


class Transolver_block_Mesh_2D(paddle.nn.Layer):
    """Transformer encoder block."""

    def __init__(self, num_heads: int, hidden_dim: int, dropout: float, act
    ='gelu', mlp_ratio=4, last_layer=False, out_dim=1, slice_num=32, H=
                 85, W=85):
        super().__init__()
        self.last_layer = last_layer
        self.ln_1 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.Attn = Physics_Attention_Structured_Mesh_2D(hidden_dim, heads=
        num_heads, dim_head=hidden_dim // num_heads, dropout=dropout,
                                                         slice_num=slice_num, H=H, W=W)
        self.ln_2 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.mlp = MLP_Mesh_2D(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                               n_layers=0, res=False, act=act)
        if self.last_layer:
            self.ln_3 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
            self.mlp2 = paddle.nn.Linear(in_features=hidden_dim,
                                         out_features=out_dim)

    def forward(self, fx):
        fx = self.Attn(self.ln_1(fx)) + fx
        fx = self.mlp(self.ln_2(fx)) + fx
        if self.last_layer:
            return self.mlp2(self.ln_3(fx))
        else:
            return fx


class Transolver_Structured_Mesh_2D(paddle.nn.Layer):

    def __init__(self,
                 input_keys: Tuple[str, ...],
                 label_keys: Tuple[str, ...],
                 weight_keys: Tuple[str, ...],
                 space_dim=1,
                 n_layers=5,
                 n_hidden=256,
                 dropout=0.0,
                 n_head=8,
                 Time_Input=False,
                 act='gelu',
                 T=None,
                 mlp_ratio=1,
                 fun_dim=1,
                 out_dim=1,
                 slice_num=32,
                 ref=8,
                 unified_pos=False,
                 H=85,
                 W=85,
                 task=None):
        super(Transolver_Structured_Mesh_2D, self).__init__()
        self.__name__ = 'Transolver_2D'
        self.input_keys = input_keys
        self.label_keys = label_keys
        self.weight_keys = weight_keys
        self.H = H
        self.W = W
        self.ref = ref
        self.T = T
        self.unified_pos = unified_pos
        self.task = task
        if self.unified_pos:
            self.pos = self.get_grid()
            self.preprocess = MLP_Mesh_2D(fun_dim + self.ref * self.ref, n_hidden * 2, n_hidden, n_layers=0, res=False,
                                          act=act)
        else:
            self.preprocess = MLP_Mesh_2D(fun_dim + space_dim, n_hidden * 2, n_hidden, n_layers=0, res=False, act=act)
        self.Time_Input = Time_Input
        self.n_hidden = n_hidden
        self.space_dim = space_dim
        if Time_Input:
            self.time_fc = paddle.nn.Sequential(
                paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
                paddle.nn.Silu(),
                paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden)
            )
        self.blocks = paddle.nn.LayerList([
            Transolver_block_Mesh_2D(
                num_heads=n_head, hidden_dim=n_hidden, dropout=dropout, act=act,
                mlp_ratio=mlp_ratio, out_dim=out_dim, slice_num=slice_num, H=H,
                W=W, last_layer=_ == n_layers - 1
            ) for _ in range(n_layers)
        ])
        self.initialize_weights()
        self.placeholder = paddle.create_parameter(
            shape=[n_hidden], dtype='float32',
            default_initializer=paddle.nn.initializer.Assign(1 / n_hidden * paddle.rand([n_hidden]))
        )

    def initialize_weights(self):
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, paddle.nn.Linear):
            trunc_normal = TruncatedNormal(mean=0.0, std=0.02)
            trunc_normal(m.weight)
            if m.bias is not None:
                constant = Constant(value=0.0)
                constant(m.bias)
        elif isinstance(m, (paddle.nn.LayerNorm, paddle.nn.BatchNorm1D)):
            constant = Constant(value=0.0)
            constant(m.bias)
            constant = Constant(value=1.0)
            constant(m.weight)

    def get_grid(self):
        # 获取网格位置信息
        h = paddle.arange(0, self.H, dtype='float32')
        w = paddle.arange(0, self.W, dtype='float32')
        grid = paddle.meshgrid(h, w)
        grid = paddle.stack(grid, axis=-1)
        grid = grid.reshape([1, -1, 2])
        return grid

    def get_grid(self, batchsize=1):
        size_x, size_y = self.H, self.W
        gridx = paddle.to_tensor(data=np.linspace(0, 1, size_x), dtype=
        'float32')
        gridx = gridx.reshape(1, size_x, 1, 1).tile(repeat_times=[batchsize,
                                                                  1, size_y, 1])
        gridy = paddle.to_tensor(data=np.linspace(0, 1, size_y), dtype=
        'float32')
        gridy = gridy.reshape(1, 1, size_y, 1).tile(repeat_times=[batchsize,
                                                                  size_x, 1, 1])
        grid = paddle.concat(x=(gridx, gridy), axis=-1)
        gridx = paddle.to_tensor(data=np.linspace(0, 1, self.ref), dtype=
        'float32')
        gridx = gridx.reshape(1, self.ref, 1, 1).tile(repeat_times=[
            batchsize, 1, self.ref, 1])
        gridy = paddle.to_tensor(data=np.linspace(0, 1, self.ref), dtype=
        'float32')
        gridy = gridy.reshape(1, 1, self.ref, 1).tile(repeat_times=[
            batchsize, self.ref, 1, 1])
        grid_ref = paddle.concat(x=(gridx, gridy), axis=-1)
        pos = paddle.sqrt(x=paddle.sum(x=(grid[:, :, :, None, None, :] -
                                          grid_ref[:, None, None, :, :, :]) ** 2, axis=-1)).reshape(batchsize
                                                                                                    , size_x, size_y,
                                                                                                    self.ref * self.ref).contiguous()
        return pos

    def forward(self, data):
        if self.task == "Pipe":
            x, fx = data[self.input_keys[0]][0], None
        elif self.task == "Darcy":
            x, fx = data[self.input_keys[0]][0], data[self.input_keys[0]][1].unsqueeze(axis=-1)
        elif self.task == "Airfoil":
            x, fx = data[self.input_keys[0]][0], None

        if self.unified_pos:
            x = self.pos.tile(repeat_times=[tuple(x.shape)[0], 1, 1, 1]
                              ).reshape(tuple(x.shape)[0], self.H * self.W, self.ref *
                                        self.ref)

        if fx is not None:
            fx = paddle.concat(x=(x, fx), axis=-1)
            fx = self.preprocess(fx)
        else:
            fx = self.preprocess(x)
            fx = fx + self.placeholder[None, None, :]
        if self.T is not None:
            Time_emb = paddle.tile(timestep_embedding(self.T, self.n_hidden), repeat_times=[1, x.shape[1], 1])
            Time_emb = self.time_fc(Time_emb)
            fx = fx + Time_emb
        for block in self.blocks:
            fx = block(fx)
        if self.task == "Pipe":
            return {self.label_keys[0]: fx.squeeze(axis=-1)}


class Physics_Attention_Irregular_Mesh_Elas(paddle.nn.Layer):

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0, slice_num=64):
        super().__init__()
        inner_dim = dim_head * heads
        self.dim_head = dim_head
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.softmax = paddle.nn.Softmax(axis=-1)
        self.dropout = paddle.nn.Dropout(p=dropout)
        self.temperature = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=paddle.ones(shape=[1, heads, 1, 1]) * 0.5)
        self.in_project_x = paddle.nn.Linear(in_features=dim, out_features=
        inner_dim)
        self.in_project_fx = paddle.nn.Linear(in_features=dim, out_features
        =inner_dim)
        self.in_project_slice = paddle.nn.Linear(in_features=dim_head,
                                                 out_features=slice_num)
        for l in [self.in_project_slice]:
            init_Orthogonal = paddle.nn.initializer.Orthogonal()
            init_Orthogonal(l.weight)
        self.to_q = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_k = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_v = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_out = paddle.nn.Sequential(paddle.nn.Linear(in_features=
                                                            inner_dim, out_features=dim), paddle.nn.Dropout(p=dropout))

    def forward(self, x):
        B, N, C = tuple(x.shape)
        fx_mid = self.in_project_fx(x).reshape(B, N, self.heads, self.dim_head
                                               ).transpose(perm=[0, 2, 1, 3]).contiguous()
        x_mid = self.in_project_x(x).reshape(B, N, self.heads, self.dim_head
                                             ).transpose(perm=[0, 2, 1, 3]).contiguous()
        slice_weights = self.softmax(self.in_project_slice(x_mid) / self.
                                     temperature)
        slice_norm = slice_weights.sum(axis=2)
        slice_token = paddle.einsum('bhnc,bhng->bhgc', fx_mid, slice_weights)
        slice_token = slice_token / (slice_norm + 1e-05)[:, :, :, None].tile(
            repeat_times=[1, 1, 1, self.dim_head])
        q_slice_token = self.to_q(slice_token)
        k_slice_token = self.to_k(slice_token)
        v_slice_token = self.to_v(slice_token)
        dots = paddle.matmul(x=q_slice_token, y=k_slice_token.transpose(
            perm=transpose_aux_func(k_slice_token.ndim, -1, -2))
                             ) * self.scale
        attn = self.softmax(dots)
        attn = self.dropout(attn)
        out_slice_token = paddle.matmul(x=attn, y=v_slice_token)
        out_x = paddle.einsum('bhgc,bhng->bhnc', out_slice_token, slice_weights
                              )
        out_x = rearrange(out_x, 'b h n d -> b n (h d)')
        return self.to_out(out_x)


class MLP_Irregular_Mesh_Elas(paddle.nn.Layer):

    def __init__(self, n_input, n_hidden, n_output, n_layers=1, act='gelu',
                 res=True):
        super(MLP_Irregular_Mesh_Elas, self).__init__()
        if act in ACTIVATION.keys():
            act = ACTIVATION[act]
        else:
            raise NotImplementedError
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output
        self.n_layers = n_layers
        self.res = res
        self.linear_pre = paddle.nn.Sequential(paddle.nn.Linear(in_features
                                                                =n_input, out_features=n_hidden), act())
        self.linear_post = paddle.nn.Linear(in_features=n_hidden,
                                            out_features=n_output)
        self.linears = paddle.nn.LayerList(sublayers=[paddle.nn.Sequential(
            paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
            act()) for _ in range(n_layers)])

    def forward(self, x):
        x = self.linear_pre(x)
        for i in range(self.n_layers):
            if self.res:
                x = self.linears[i](x) + x
            else:
                x = self.linears[i](x)
        x = self.linear_post(x)
        return x


class Transolver_block_Irregular_Mesh_Elas(paddle.nn.Layer):
    """Transformer encoder block."""

    def __init__(self, num_heads: int, hidden_dim: int, dropout: float, act
    ='gelu', mlp_ratio=4, last_layer=False, out_dim=1, slice_num=32):
        super().__init__()
        self.last_layer = last_layer
        self.ln_1 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.Attn = Physics_Attention_Irregular_Mesh_Elas(hidden_dim, heads=
        num_heads, dim_head=hidden_dim // num_heads, dropout=dropout,
                                                     slice_num=slice_num)
        self.ln_2 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.mlp = MLP_Irregular_Mesh_Elas(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                                      n_layers=0, res=False, act=act)
        if self.last_layer:
            self.ln_3 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
            self.mlp2 = paddle.nn.Linear(in_features=hidden_dim,
                                         out_features=out_dim)

    def forward(self, fx):
        fx = self.Attn(self.ln_1(fx)) + fx
        fx = self.mlp(self.ln_2(fx)) + fx
        if self.last_layer:
            return self.mlp2(self.ln_3(fx))
        else:
            return fx


def timestep_embedding(timesteps, dim, max_period=10000, repeat_only=False):
    """
    Create sinusoidal timestep embeddings.
    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional.
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
    half = dim // 2
    freqs = paddle.exp(x=-math.log(max_period) * paddle.arange(start=0, end
    =half, dtype='float32') / half)
    args = timesteps[:, None].astype(dtype='float32') * freqs[None]
    embedding = paddle.concat(x=[paddle.cos(x=args), paddle.sin(x=args)],
                              axis=-1)
    if dim % 2:
        embedding = paddle.concat(x=[embedding, paddle.zeros_like(x=
                                                                  embedding[:, :1])], axis=-1)
    return embedding


class Transolver_Irregular_Mesh_Elas(paddle.nn.Layer):

    def __init__(self,
                 input_keys: Tuple[str, ...],
                 label_keys: Tuple[str, ...],
                 weight_keys: Tuple[str, ...],
                 space_dim=1,
                 n_layers=5,
                 n_hidden=256,
                 dropout=0.0,
                 n_head=8,
                 Time_Input=False,
                 act='gelu',
                 mlp_ratio=1,
                 fun_dim=1,
                 out_dim=1,
                 slice_num=32,
                 ref=8,
                 unified_pos=False,
                 T=None):
        super(Transolver_Irregular_Mesh_Elas, self).__init__()
        self.__name__ = 'Transolver_1D'
        self.input_keys = input_keys
        self.label_keys = label_keys
        self.weight_keys = weight_keys
        self.ref = ref
        self.unified_pos = unified_pos
        self.Time_Input = Time_Input
        self.n_hidden = n_hidden
        self.space_dim = space_dim
        self.T = T
        if self.unified_pos:
            self.preprocess = MLP_Irregular_Mesh_Elas(fun_dim + self.ref * self.ref, n_hidden * 2, n_hidden, n_layers=0,
                                                 res=False, act=act)
        else:
            self.preprocess = MLP_Irregular_Mesh_Elas(fun_dim + space_dim, n_hidden * 2, n_hidden, n_layers=0, res=False,
                                                 act=act)
        if Time_Input:
            self.time_fc = paddle.nn.Sequential(
                paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
                paddle.nn.Silu(),
                paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden)
            )
        self.blocks = paddle.nn.LayerList([
            Transolver_block_Irregular_Mesh_Elas(
                num_heads=n_head, hidden_dim=n_hidden, dropout=dropout, act=act,
                mlp_ratio=mlp_ratio, out_dim=out_dim, slice_num=slice_num,
                last_layer=_ == n_layers - 1
            ) for _ in range(n_layers)
        ])
        self.initialize_weights()
        self.placeholder = paddle.create_parameter(
            shape=[n_hidden], dtype='float32',
            default_initializer=paddle.nn.initializer.Assign(1 / n_hidden * paddle.rand([n_hidden]))
        )

    def initialize_weights(self):
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, paddle.nn.Linear):
            trunc_normal = TruncatedNormal(mean=0.0, std=0.02)
            trunc_normal(m.weight)
            if m.bias is not None:
                constant = Constant(value=0.0)
                constant(m.bias)
        elif isinstance(m, (paddle.nn.LayerNorm, paddle.nn.BatchNorm1D)):
            constant = Constant(value=0.0)
            constant(m.bias)
            constant = Constant(value=1.0)
            constant(m.weight)

    def get_grid(self, x, batchsize=1):
        gridx = paddle.to_tensor(data=np.linspace(0, 1, self.ref), dtype=
        'float32')
        gridx = gridx.reshape(1, self.ref, 1, 1).tile(repeat_times=[
            batchsize, 1, self.ref, 1])
        gridy = paddle.to_tensor(data=np.linspace(0, 1, self.ref), dtype=
        'float32')
        gridy = gridy.reshape(1, 1, self.ref, 1).tile(repeat_times=[
            batchsize, self.ref, 1, 1])
        grid_ref = paddle.concat(x=(gridx, gridy), axis=-1).reshape(batchsize, self.ref * self.ref, 2)
        pos = paddle.sqrt(x=paddle.sum(x=(x[:, :, None, :] - grid_ref[:,
                                                             None, :, :]) ** 2, axis=-1)).reshape(batchsize,
                                                                                                  tuple(x.shape)[
                                                                                                      1],
                                                                                                  self.ref * self.ref).contiguous()
        return pos

    def forward(self, data):
        x, fx = data[self.input_keys[0]][0], None
        if self.unified_pos:
            x = self.get_grid(x, tuple(x.shape)[0])
        if fx is not None:
            fx = paddle.concat(x=(x, fx), axis=-1)
            fx = self.preprocess(fx)
        else:
            fx = self.preprocess(x)
        fx = fx + self.placeholder[None, None, :]
        if self.T is not None:
            Time_emb = timestep_embedding(self.T, self.n_hidden).repeat(1, tuple
            (x.shape)[1], 1)
            Time_emb = self.time_fc(Time_emb)
            fx = fx + Time_emb
        for block in self.blocks:
            fx = block(fx)
        return {self.label_keys[0]: fx.squeeze(axis=-1)}


class Physics_Attention_Irregular_Mesh(paddle.nn.Layer):

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0, slice_num=64):
        super().__init__()
        inner_dim = dim_head * heads
        self.dim_head = dim_head
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.softmax = paddle.nn.Softmax(axis=-1)
        self.dropout = paddle.nn.Dropout(p=dropout)
        self.temperature = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=paddle.ones(shape=[1, heads, 1, 1]) * 0.5)
        self.in_project_x = paddle.nn.Linear(in_features=dim, out_features=
        inner_dim)
        self.in_project_fx = paddle.nn.Linear(in_features=dim, out_features
        =inner_dim)
        self.in_project_slice = paddle.nn.Linear(in_features=dim_head,
                                                 out_features=slice_num)
        for l in [self.in_project_slice]:
            init_Orthogonal = paddle.nn.initializer.Orthogonal()
            init_Orthogonal(l.weight)
        self.to_q = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_k = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_v = paddle.nn.Linear(in_features=dim_head, out_features=
        dim_head, bias_attr=False)
        self.to_out = paddle.nn.Sequential(paddle.nn.Linear(in_features=
                                                            inner_dim, out_features=dim), paddle.nn.Dropout(p=dropout))

    def forward(self, x):
        B, N, C = tuple(x.shape)
        fx_mid = self.in_project_fx(x).reshape(B, N, self.heads, self.dim_head
                                               ).transpose(perm=[0, 2, 1, 3]).contiguous()
        x_mid = self.in_project_x(x).reshape(B, N, self.heads, self.dim_head
                                             ).transpose(perm=[0, 2, 1, 3]).contiguous()
        slice_weights = self.softmax(self.in_project_slice(x_mid) / self.
                                     temperature)
        slice_norm = slice_weights.sum(axis=2)
        slice_token = paddle.einsum('bhnc,bhng->bhgc', fx_mid, slice_weights)
        slice_token = slice_token / (slice_norm + 1e-05)[:, :, :, None].tile(
            repeat_times=[1, 1, 1, self.dim_head])
        q_slice_token = self.to_q(slice_token)
        k_slice_token = self.to_k(slice_token)
        v_slice_token = self.to_v(slice_token)
        dots = paddle.matmul(x=q_slice_token, y=k_slice_token.transpose(
            perm=transpose_aux_func(k_slice_token.ndim, -1, -2))
                             ) * self.scale
        attn = self.softmax(dots)
        attn = self.dropout(attn)
        out_slice_token = paddle.matmul(x=attn, y=v_slice_token)
        out_x = paddle.einsum('bhgc,bhng->bhnc', out_slice_token, slice_weights
                              )
        out_x = rearrange(out_x, 'b h n d -> b n (h d)')
        return self.to_out(out_x)


class MLP_Airfoil(paddle.nn.Layer):

    def __init__(self, n_input, n_hidden, n_output, n_layers=1, act='gelu',
                 res=True):
        super(MLP_Airfoil, self).__init__()
        if act in ACTIVATION.keys():
            act = ACTIVATION[act]
        else:
            raise NotImplementedError
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output
        self.n_layers = n_layers
        self.res = res
        self.linear_pre = paddle.nn.Sequential(paddle.nn.Linear(in_features
                                                                =n_input, out_features=n_hidden), act())
        self.linear_post = paddle.nn.Linear(in_features=n_hidden,
                                            out_features=n_output)
        self.linears = paddle.nn.LayerList(sublayers=[paddle.nn.Sequential(
            paddle.nn.Linear(in_features=n_hidden, out_features=n_hidden),
            act()) for _ in range(n_layers)])

    def forward(self, x):
        x = self.linear_pre(x)
        for i in range(self.n_layers):
            if self.res:
                x = self.linears[i](x) + x
            else:
                x = self.linears[i](x)
        x = self.linear_post(x)
        return x


class Transolver_block_Airfoil(paddle.nn.Layer):
    """Transformer encoder block."""

    def __init__(self, num_heads: int, hidden_dim: int, dropout: float, act
    ='gelu', mlp_ratio=4, last_layer=False, out_dim=1, slice_num=32):
        super().__init__()
        self.last_layer = last_layer
        self.ln_1 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.Attn = Physics_Attention_Irregular_Mesh(hidden_dim, heads=
        num_heads, dim_head=hidden_dim // num_heads, dropout=dropout,
                                                             slice_num=slice_num)
        self.ln_2 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
        self.mlp = MLP_Airfoil(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                               n_layers=0, res=False, act=act)
        self.mlp_new = MLP_Airfoil(hidden_dim, hidden_dim * mlp_ratio, hidden_dim,
                                   n_layers=0, res=False, act=act)
        if self.last_layer:
            self.ln_3 = paddle.nn.LayerNorm(normalized_shape=hidden_dim)
            self.mlp2 = paddle.nn.Linear(in_features=hidden_dim,
                                         out_features=out_dim)

    def forward(self, fx):
        fx = self.Attn(self.ln_1(fx)) + fx
        fx = self.mlp(self.ln_2(fx)) + fx
        if self.last_layer:
            return self.mlp2(self.ln_3(fx))
        else:
            return fx


class Transolver_Airfoil(paddle.nn.Layer):

    def __init__(self,
                 input_keys: Tuple[str, ...],
                 label_keys: Tuple[str, ...],
                 weight_keys: Tuple[str, ...],
                 space_dim=1,
                 n_layers=5,
                 n_hidden=256,
                 dropout=0,
                 n_head=8,
                 act='gelu',
                 mlp_ratio=1,
                 fun_dim=1,
                 out_dim=1,
                 slice_num=32,
                 ref=8,
                 unified_pos=False,
                 device='gpu'):
        super(Transolver_Airfoil, self).__init__()
        self.__name__ = 'Transolver'
        self.input_keys = input_keys
        self.label_keys = label_keys
        self.weight_keys = weight_keys
        self.ref = ref
        self.device = device
        self.unified_pos = unified_pos
        if self.unified_pos:
            self.preprocess = MLP_Airfoil(fun_dim + space_dim + self.ref * self.ref,
                                          n_hidden * 2, n_hidden, n_layers=0, res=False, act=act)
        else:
            self.preprocess = MLP_Airfoil(fun_dim + space_dim, n_hidden * 2,
                                          n_hidden, n_layers=0, res=False, act=act)
        self.n_hidden = n_hidden
        self.space_dim = space_dim
        self.blocks = paddle.nn.LayerList(sublayers=[Transolver_block_Airfoil(
            num_heads=n_head, hidden_dim=n_hidden, dropout=dropout, act=act,
            mlp_ratio=mlp_ratio, out_dim=out_dim, slice_num=slice_num,
            last_layer=_ == n_layers - 1) for _ in range(n_layers)])
        self.initialize_weights()
        self.placeholder = paddle.base.framework.EagerParamBase.from_tensor(
            tensor=1 / n_hidden * paddle.rand(shape=[n_hidden], dtype='float32'))

    def initialize_weights(self):
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, paddle.nn.Linear):
            trunc_normal = TruncatedNormal(mean=0.0, std=0.02)
            trunc_normal(m.weight)
            if m.bias is not None:
                constant = Constant(value=0.0)
                constant(m.bias)
        elif isinstance(m, (paddle.nn.LayerNorm, paddle.nn.BatchNorm1D)):
            constant = Constant(value=0.0)
            constant(m.bias)
            constant = Constant(value=1.0)
            constant(m.weight)

    def get_grid(self, my_pos):
        batchsize = tuple(my_pos.shape)[0]
        gridx = paddle.to_tensor(data=np.linspace(-2, 4, self.ref), dtype=
        'float32')
        gridx = gridx.reshape(1, self.ref, 1, 1).tile(repeat_times=[
            batchsize, 1, self.ref, 1])
        gridy = paddle.to_tensor(data=np.linspace(-1.5, 1.5, self.ref),
                                 dtype='float32')
        gridy = gridy.reshape(1, 1, self.ref, 1).tile(repeat_times=[
            batchsize, self.ref, 1, 1])
        grid_ref = paddle.concat(x=(gridx, gridy), axis=-1).reshape([batchsize, self.ref ** 2, 2])
        pos = paddle.sqrt(x=paddle.sum(x=(my_pos[:, :, None, :] - grid_ref[
                                                                  :, None, :, :]) ** 2, axis=-1)).reshape(batchsize,
                                                                                                          tuple(my_pos
                                                                                                                .shape)[
                                                                                                              1],
                                                                                                          self.ref * self.ref).contiguous()
        return pos

    def forward(self, data):
        x, edge_index, pos, surf = data[self.input_keys[0]], data[self.input_keys[1]], data[self.input_keys[3]],  data[self.input_keys[4]],
        fx = None

        # x, fx, T = data.x, None, None

        x = paddle.cast(x, dtype="float32")

        x = x[None, :, :]
        if self.unified_pos:
            new_pos = self.get_grid(pos[None, :, :])
            # print(f"x origin dtype: {x.dtype}, new_pos origin dtype: {new_pos.dtype}")
            x = paddle.concat(x=(x, new_pos), axis=-1)
        if fx is not None:
            fx = paddle.concat(x=(x, fx), axis=-1)
            fx = self.preprocess(fx)
        else:
            fx = self.preprocess(x)
            fx = fx + self.placeholder[None, None, :]
        for block in self.blocks:
            fx = block(fx)
        return {self.label_keys[0]: fx[0][~surf, :], self.label_keys[1]: fx[0][surf, :]}
